---
- name: Update apt cache and install Docker dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Install Docker Engine
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: Create or update Docker daemon.json
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        },
        "no-new-priviledges": true,
        "live-restore": true
      }
    mode: '0644'

- name: Ensure Docker is installed and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create Palworld directory on host
  ansible.builtin.file:
    path: "{{ server_data_dir }}"
    state: directory
    mode: '0755'
    owner: '1000'
    group: '1000'

- name: Create Palworld server directory on host
  ansible.builtin.file:
    path: "{{ server_data_dir }}/palworld_server"
    state: directory
    mode: '0755'
    owner: '1000'
    group: '1000'

- name: Create Palworld backup directory on host
  ansible.builtin.file:
    path: "{{ server_data_dir }}/backups"
    state: directory
    mode: '0755'
    owner: '1000'
    group: '1000'

- name: Create Palworld logs directory on host
  ansible.builtin.file:
    path: "{{ server_data_dir }}/logs"
    state: directory
    mode: '0755'
    owner: '1000'
    group: '1000'

- name: Run Palworld Docker container
  community.docker.docker_container:
    name: palworld-server
    image: supersunho/palworld-server:latest
    state: started
    restart_policy: unless-stopped
    ports:
      - "8211:8211/udp"
    volumes:
      - "{{ server_data_dir }}/backups:/home/steam/backups"
      - "{{ server_data_dir }}/palworld_server:/home/steam/palworld_server/Pal"
    env:
      PUID: "1000"
      PGID: "1000"
      MAX_PLAYERS: "32"
      LANGUAGE: "en"
      TZ: "{{ timezone }}"
      SERVER_NAME: "{{ server_name }}"
      SERVER_PASSWORD: "{{ server_password }}"
      ADMIN_PASSWORD: "{{ admin_password }}"
      RCON_ENABLED: "true"
      IDLE_RESTART_ENABLED: "false"
      IS_MULTIPLAY: "true"
      ENABLE_PUBLIC_LOBBY: "true"
      IS_START_LOCATION_SELECT_BY_MAP: "false"