---
- name: Restart Palworld Docker Container
  hosts: palworld_servers
  become: true

  tasks:
    - name: Restart Palworld container
      community.docker.docker_container:
        name: palworld-server
        restart: true
        state: started